#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -e /qsub_out/faerror.txt
#PBS -o /qsub_out/faoutput.txt
cd $PBS_O_WORKDIR

for m in 0 1 2
do
    for u in 0.20 0.30 0.50
    do
        for e in -0.0 -$u
        do
            for g in 0.001 0.01
            do
                for a in 0.4 0.75 
                do
                    for t in 0.010
                    do
                        if [[ ${m} -eq 2 ]]
                        then
                            for k in 1.0 10.0
                            do
                                for z in 1.0
                                do
                                    echo fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}_k${k}_z${z}.pdf
                                    python fit_average.py -c 20 -m $m -u $u -e $e -g $g -a $a -t $t
                                    mv fit_average.pdf fitavg/fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}_k${k}_z${z}.pdf
#                                     chromium fitavg/fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}_k${k}_z${z}.pdf
                                done
                            done
                        else
                            echo fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}.pdf
                            python fit_average.py -c 20 -m $m -u $u -e $e -g $g -a $a -t $t
                            mv fit_average.pdf fitavg/fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}.pdf
#                             chromium fitavg/fit_average_m${m}_u${u}_e${e}_g${g}_a${a}_t${t}.pdf
                        fi
                    done
                done
            done
        done
    done
done
echo "Finished Fit Average" | mailx -s " Fit Average Finished" joskodeboer@gmail.com
