#!/bin/bash 
ulimit -s 8192
#spinfull 0
python fit_average.py -c 4 -m 2 -u 0.30 -e -0.0 -g 0.01 -a 0.40 -t 0.01
mv fit_average.pdf fitavg/fit_spinfull_0.pdf
chromium fitavg/fit_spinfull_0.pdf
#spinfull 1
python fit_average.py -c 4 -m 2 -u 0.30 -e -.30 -g 0.01 -a 0.40 -t 0.01
mv fit_average.pdf fitavg/fit_spinfull_1.pdf
chromium fitavg/fit_spinfull_1.pdf
#spinfull 2
python fit_average.py -c 4 -m 2 -u 0.50 -e -0.0 -g 0.01 -a 0.40 -t 0.01
mv fit_average.pdf fitavg/fit_spinfull_2.pdf
chromium fitavg/fit_spinfull_2.pdf
#spinfull 3
python fit_average.py -c 4 -m 2 -u 0.50 -e -0.50 -g 0.01 -a 0.40 -t 0.01
mv fit_average.pdf fitavg/fit_spinfull_3.pdf
chromium fitavg/fit_spinfull_3.pdf
#spinless 0
python fit_average.py -c 4 -m 1 -u 0.20 -e -0.00 -g 0.01 -a 0.40 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_0.pdf
chromium fitavg/fit_spinless_0.pdf
#spinless  1
python fit_average.py -c 4 -m 1 -u 0.20 -e -0.20 -g 0.001 -a 0.75 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_1.pdf
chromium fitavg/fit_spinless_1.pdf
#spinless  2
python fit_average.py -c 4 -m 1 -u 0.20 -e -0.20 -g 0.01 -a 0.4 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_2.pdf
chromium fitavg/fit_spinless_2.pdf
#spinless  3
python fit_average.py -c 4 -m 1 -u 0.20 -e -0.20 -g 0.01 -a 0.75 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_3.pdf
chromium fitavg/fit_spinless_3.pdf
#spinless  4
python fit_average.py -c 4 -m 1 -u 0.30 -e -0.0 -g 0.01 -a 0.4 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_4.pdf
chromium fitavg/fit_spinless_4.pdf
#spinless  5
python fit_average.py -c 4 -m 1 -u 0.30 -e -0.30 -g 0.01 -a 0.4 -t 0.01
mv fit_average.pdf fitavg/fit_spinless_5.pdf
chromium fitavg/fit_spinless_5.pdf 