#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -e /qsub_out/error.txt
#PBS -o /qsub_out/output.txt
cd $PBS_O_WORKDIR

python perspin_current_maps_parallel.py -k 0.0 -c 20 
python perspin_current_maps_parallel.py -k 1.0 -c 20 
python perspin_current_maps_parallel.py -k 2.0 -c 20 
python perspin_current_maps_parallel.py -k 5.0 -c 20 
python perspin_current_maps_parallel.py -k 10.0 -c 20 
python perspin_current_maps_parallel.py -k 100.0 -c 20 
python perspin_current_maps_parallel.py -k 100000.0 -c 20 
